export const readableUnits = {
  litre: 'Litre',
  millilitre: 'Millilitre',
  ounce: 'Ounce',
  gallon: 'Gallon',
  quart: 'Quart',
  pint: 'Pint',
  cup: 'Cup',
  tablespoon: 'Tablespoon',
  teaspoon: 'Teaspoon',
  cubic_foot: 'Cubic Feet',
  cubic_inch: 'Cubic Inch',
  cubic_meter: 'Cubic Meter',
  gallon_us: 'US Gallon',
  quart_us: 'US Quart',
  pint_us: 'US Pint',
  cup_us: 'US Cup',
  tablespoon_us: 'US Tablespoon',
  teaspoon_us: 'US Teaspoon',
  nanosecond: 'Nanosecond',
  microsecond: 'Microsecond',
  millisecond: 'Millisecond',
  second: 'Second',
  minute: 'Minute',
  hour: 'Hour',
  day: 'Day',
  week: 'Week',
  month: 'Month',
  year: 'Year',
  decade: 'Decade',
  century: 'Century',
  celcius: 'Celcius',
  fahrenheit: 'Fahrenheit',
  kelvin: 'Kelvin',
  kilometre_per_hour: 'Kilometre per hour',
  mile_per_hour: 'Mile per hour',
  foot_per_second: 'Feet per second',
  meter_per_second: 'Meter per second',
  knot: 'Knots',
  bar: 'Bar',
  pascal: 'Pascal',
  pound_per_square_inch: 'Pound per square inch',
  atmosphere: 'Atmospheric',
  torr: 'Torr',
  degree: 'Degree',
  gradian: 'Gradian',
  milliradian: 'Milliradian',
  minute_of_arc: 'Minute of Arc',
  radian: 'Radian',
  second_of_arc: 'Second of Arc',
  kilogram: 'Kilogram',
  tonne: 'Tonne',
  gram: 'Gram',
  milligram: 'Milligram',
  microgram: 'Microgram',
  ton: 'Ton',
  ton_us: 'US Ton',
  stone: 'Stone',
  pound: 'Pound',
  metre: 'Metre',
  kilometre: 'Kilometre',
  centimeter: 'Centimetre',
  millimetre: 'Millimetre',
  nanometre: 'Nanometre',
  mile: 'Mile',
  yard: 'Yard',
  foot: 'Foot',
  inch: 'Inch',
  nautical_mile: 'Nautical Mile',
  miles_per_gallon: 'Miles per Gallon',
  miles_per_gallon_us: 'Miles per US Gallon',
  kilometre_per_litre: 'Kilometre per Litre',
  litre_per_100_kilometre: 'Litre per 100 Kilometre',
  hertz: 'Hertz',
  kilohertz: 'Kilohertz',
  megahertz: 'Megahertz',
  gigahertz: 'Gigahertz',
  joule: 'Joule',
  kilojoule: 'Kilojoule',
  gram_calorie: 'Gram Calorie',
  kilocalorie: 'Kilocalorie',
  watt_hour: 'Watt hour',
  kilowatt_hour: 'Kilowatt hour',
  electronvolt: 'Electronvolt',
  thermal_unit: 'Thermal unit',
  therm_us: 'US Therm',
  foot_pound: 'Foot pound',
  bit: 'Bit',
  kilobit: 'Kilobit',
  kibibit: 'Kibibit',
  megabit: 'Megabit',
  mebibit: 'Mebibit',
  gigabit: 'Gigabit',
  gibibit: 'Gibibit',
  terabit: 'Terabit',
  tebibit: 'Tebibit',
  petabit: 'Petabit',
  petibit: 'Petibit',
  byte: 'Byte',
  kilobyte: 'Kilobyte',
  kibibyte: 'Kibibyte',
  megabyte: 'Megabyte',
  mebibyte: 'Mebibyte',
  gigabyte: 'Gigabyte',
  gibibyte: 'Gibibyte',
  terabyte: 'Terabyte',
  tebibyte: 'Tebibyte',
  petabyte: 'Petabyte',
  pebibyte: 'Pebibyte',
  bit_per_second: 'Bits per second',
  kilobit_per_second: 'Kilobit per Second',
  kilobyte_per_second: 'Kilobyte per Second',
  kibibit_per_second: 'Kibibit per Second',
  megabit_per_second: 'Megabit per Second',
  megabyte_per_second: 'Megabyte per Second',
  mebibit_per_second: 'Mebibit per Second',
  gigabit_per_second: 'Gigabit per Second',
  gigabyte_per_second: 'Gigabyte per Second',
  gibibit_per_second: 'Gibibit per Second',
  terabit_per_second: 'Terabit per Second',
  terabyte_per_second: 'Terabyte per Second',
  tebibit_per_second: 'Tebibit per Second',
  square_meter: 'Square meter',
  square_kilometer: 'Square Kilometer',
  square_mile: 'Square Mile',
  square_yard: 'Squre Yard',
  square_foot: 'Square Foot',
  square_inch: 'Square Inch',
  hectare: 'Hectare',
  acre: 'Acre',
  newton_meter: 'Newton meter',
  deca_newton_meter: 'Deca newton meter',
  kilo_newton_meter: 'Kilo newton meter',
  deci_newton_meter: 'Deci newton meter',
  centi_newton_meter: 'Centi newton meter',
  milli_newton_meter: 'Milli newton meter',
  micro_newton_meter: 'Micro newton meter',
  newton_millimeter: 'Newton millimeter',
  kilogram_force_meter: 'Kilogram force meter',
  kilogram_force_centimeter: 'Kilogram force cenimeter',
  gram_force_meter: 'Gram force meter',
  gram_force_centimeter: 'Gram force centimeter',
  dyne_centimeter: 'Dyne centimeter',
  inch_pound: 'Inch pound',
  inch_ounce: 'Inch ounce',
  kilogram_per_cubic_meter: 'Kilogram per cubic meter',
  kilogram_per_cubic_millimeter: 'Kilogram per cubic millimeter',
  kilogram_per_cubic_centimeter: 'Kilogram per cubic centimeter',
  gram_per_cubic_meter: 'Gram per cubic meter',
  gram_per_cubic_millimeter: 'Gram per cubic millimeter',
  gram_per_cubic_centimeter: 'Gram per cubic centimeter',
  tonne_per_cubic_meter: 'Tonne per cubic meter',
  tonne_per_cubic_millimeter: 'Tonne per cubic millimeter',
  tonne_per_cubic_centimeter: 'Tonne per cubic centimeter',
  gram_per_liter: 'Gram per litre',
  gram_per_milliliter: 'Gram per millitre',
  pound_per_cubic_feet: 'Pound per cubic feet',
  pound_per_cubic_inch: 'Pound per cubic inch'
}
